#Install Libraries

In [1]:
#download and install langchain dependencies
!pip install -qU langchain-community faiss-cpu langchain-openai

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 27.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.8/23.8 MB 44.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.5/88.5 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 21.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 1.7 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.33.1 which is incompatible.

In [2]:
# importing all libraries needed
import pandas as pd #for data processing

import faiss #for faiss vector database
from langchain_community.docstore.in_memory import InMemoryDocstore #for allocating vector database storage (in RAM)
from langchain_community.vectorstores import FAISS #for langchain - faiss vector database connector

from langchain_openai import OpenAIEmbeddings, ChatOpenAI #for embedding and LLM service
from uuid import uuid4 #for generate id with uuid format

from langchain_core.documents import Document #for document format that stored to vector database collection

In [3]:
import getpass #for input password interface
import os #for read and manage python directory path and environment

from google.colab import userdata

# input openai api key
if userdata.get('OPENAI_API_KEY'):
  os.environ["OPENAI_API_KEY"] = userdata.get('OPENAI_API_KEY')
else:
  os.environ["OPENAI_API_KEY"] = getpass.getpass("Enter API key for OpenAI: ")

In [4]:
#define embedding model and llm from openai provider
embeddings = OpenAIEmbeddings(model="text-embedding-3-small")
llm = ChatOpenAI(model="gpt-4o-mini")

#Read and Store Data to Vector Database

In [5]:
#directory to dataset
data_path = "/content/drive/MyDrive/JCAIEAH-003/Notes and Hands On/Modul 3/Day 10/flipkart_com-ecommerce_sample.csv"

In [6]:
#read dataset with pandas
df = pd.read_csv(data_path)
print(df.shape) #show total row and column with format (row, column)
df.head() #show first 5 record of dataset

(20000, 15)

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price,discounted_price,image,is_FK_Advantage_product,description,product_rating,overall_rating,brand,product_specifications
0,c2d766ca982eca8304150849735ffef9,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,"[""http://img5a.flixcart.com/image/short/u/4/a/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
1,7f7036a6d550aaa89d34c77bd39a5e48,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",False,FabHomeDecor Fabric Double Sofa Bed (Finish Co...,No rating available,No rating available,FabHomeDecor,"{""product_specification""=>[{""key""=>""Installati..."
2,f449ec65dcbc041b6ae5e6a32717d01b,2016-03-25 22:59:23 +0000,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",False,Key Features of AW Bellies Sandals Wedges Heel...,No rating available,No rating available,AW,"{""product_specification""=>[{""key""=>""Ideal For""..."
3,0973b37acd0c664e3de26e97e5571454,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.0,267.0,"[""http://img5a.flixcart.com/image/short/6/2/h/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,2016-03-25 22:59:23 +0000,http://www.flipkart.com/sicons-all-purpose-arn...,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",PSOEH3ZYDMSYARJ5,220.0,210.0,"[""http://img5a.flixcart.com/image/pet-shampoo/...",False,Specifications of Sicons All Purpose Arnica Do...,No rating available,No rating available,Sicons,"{""product_specification""=>[{""key""=>""Pet Type"",..."

In [7]:
data = df.copy() #copy data table
data = data.iloc[:500,].reset_index(drop=True) #take row 1 to row 500 from table
data.head() #show first 5 record of dataset

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price,discounted_price,image,is_FK_Advantage_product,description,product_rating,overall_rating,brand,product_specifications
0,c2d766ca982eca8304150849735ffef9,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,"[""http://img5a.flixcart.com/image/short/u/4/a/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
1,7f7036a6d550aaa89d34c77bd39a5e48,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",False,FabHomeDecor Fabric Double Sofa Bed (Finish Co...,No rating available,No rating available,FabHomeDecor,"{""product_specification""=>[{""key""=>""Installati..."
2,f449ec65dcbc041b6ae5e6a32717d01b,2016-03-25 22:59:23 +0000,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",False,Key Features of AW Bellies Sandals Wedges Heel...,No rating available,No rating available,AW,"{""product_specification""=>[{""key""=>""Ideal For""..."
3,0973b37acd0c664e3de26e97e5571454,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.0,267.0,"[""http://img5a.flixcart.com/image/short/6/2/h/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,2016-03-25 22:59:23 +0000,http://www.flipkart.com/sicons-all-purpose-arn...,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",PSOEH3ZYDMSYARJ5,220.0,210.0,"[""http://img5a.flixcart.com/image/pet-shampoo/...",False,Specifications of Sicons All Purpose Arnica Do...,No rating available,No rating available,Sicons,"{""product_specification""=>[{""key""=>""Pet Type"",..."

In [11]:
#set up index for data to be stored in vector database
index = faiss.IndexFlatL2(len(embeddings.embed_query("JC Generative AI")))

#set up vector store with faiss vector database
#this vector store will helps you to maintain vector database, such as insert new data, delete, modify, etc.
vector_store = FAISS(
    embedding_function=embeddings,
    index=index,
    docstore=InMemoryDocstore(),
    index_to_docstore_id={},
)

In [12]:
for i,e in enumerate(data.iterrows()):
  print(f"Processing data : {i}")
  unique_id = e[1]['uniq_id']
  product_name = e[1]['product_name']
  description = str(e[1]['description']) if pd.notna(e[1]['description']) else "" # Ensure description is a string and handle NaN
  document = Document(
      page_content=description,
      metadata={
          "uniq_id": str(unique_id),
          "product_name": product_name
          },
  )
  vector_store.add_documents(documents=[document], ids=[unique_id])

Processing data : 0
Processing data : 1
Processing data : 2
Processing data : 3
Processing data : 4
Processing data : 5
Processing data : 6
Processing data : 7
Processing data : 8
Processing data : 9
Processing data : 10
Processing data : 11
Processing data : 12
Processing data : 13
Processing data : 14
Processing data : 15
Processing data : 16
Processing data : 17
Processing data : 18
Processing data : 19
Processing data : 20
Processing data : 21
Processing data : 22
Processing data : 23
Processing data : 24
Processing data : 25
Processing data : 26
Processing data : 27
Processing data : 28
Processing data : 29
Processing data : 30
Processing data : 31
Processing data : 32
Processing data : 33
Processing data : 34
Processing data : 35
Processing data : 36
Processing data : 37
Processing data : 38
Processing data : 39
Processing data : 40
Processing data : 41
Processing data : 42
Processing data : 43
Processing data : 44
Processing data : 45
Processing data : 46
Processing data : 47
Processing data : 48
Processing data : 49
Processing data : 50
Processing data : 51
Processing data : 52
Processing data : 53
Processing data : 54
Processing data : 55
Processing data : 56
Processing data : 57
Processing data : 58
Processing data : 59
Processing data : 60
Processing data : 61
Processing data : 62
Processing data : 63
Processing data : 64
Processing data : 65
Processing data : 66
Processing data : 67
Processing data : 68
Processing data : 69
Processing data : 70
Processing data : 71
Processing data : 72
Processing data : 73
Processing data : 74
Processing data : 75
Processing data : 76
Processing data : 77
Processing data : 78
Processing data : 79
Processing data : 80
Processing data : 81
Processing data : 82
Processing data : 83
Processing data : 84
Processing data : 85
Processing data : 86
Processing data : 87
Processing data : 88
Processing data : 89
Processing data : 90
Processing data : 91
Processing data : 92
Processing data : 93
Processing data : 94
Processing data : 95
Processing data : 96
Processing data : 97
Processing data : 98
Processing data : 99
Processing data : 100
Processing data : 101
Processing data : 102
Processing data : 103
Processing data : 104
Processing data : 105
Processing data : 106
Processing data : 107
Processing data : 108
Processing data : 109
Processing data : 110
Processing data : 111
Processing data : 112
Processing data : 113
Processing data : 114
Processing data : 115
Processing data : 116
Processing data : 117
Processing data : 118
Processing data : 119
Processing data : 120
Processing data : 121
Processing data : 122
Processing data : 123
Processing data : 124
Processing data : 125
Processing data : 126
Processing data : 127
Processing data : 128
Processing data : 129
Processing data : 130
Processing data : 131
Processing data : 132
Processing data : 133
Processing data : 134
Processing data : 135
Processing data : 136
Processing data : 137
Processing data : 138
Processing data : 139
Processing data : 140
Processing data : 141
Processing data : 142
Processing data : 143
Processing data : 144
Processing data : 145
Processing data : 146
Processing data : 147
Processing data : 148
Processing data : 149
Processing data : 150
Processing data : 151
Processing data : 152
Processing data : 153
Processing data : 154
Processing data : 155
Processing data : 156
Processing data : 157
Processing data : 158
Processing data : 159
Processing data : 160
Processing data : 161
Processing data : 162
Processing data : 163
Processing data : 164
Processing data : 165
Processing data : 166
Processing data : 167
Processing data : 168
Processing data : 169
Processing data : 170
Processing data : 171
Processing data : 172
Processing data : 173
Processing data : 174
Processing data : 175
Processing data : 176
Processing data : 177
Processing data : 178
Processing data : 179
Processing data : 180
Processing data : 181
Processing data : 182
Processing data : 183
Processing data : 184
Processing data : 185
Processing data : 186
Processing data : 187
Processing data : 188
Processing data : 189
Processing data : 190
Processing data : 191
Processing data : 192
Processing data : 193
Processing data : 194
Processing data : 195
Processing data : 196
Processing data : 197
Processing data : 198
Processing data : 199
Processing data : 200
Processing data : 201
Processing data : 202
Processing data : 203
Processing data : 204
Processing data : 205
Processing data : 206
Processing data : 207
Processing data : 208
Processing data : 209
Processing data : 210
Processing data : 211
Processing data : 212
Processing data : 213
Processing data : 214
Processing data : 215
Processing data : 216
Processing data : 217
Processing data : 218
Processing data : 219
Processing data : 220
Processing data : 221
Processing data : 222
Processing data : 223
Processing data : 224
Processing data : 225
Processing data : 226
Processing data : 227
Processing data : 228
Processing data : 229
Processing data : 230
Processing data : 231
Processing data : 232
Processing data : 233
Processing data : 234
Processing data : 235
Processing data : 236
Processing data : 237
Processing data : 238
Processing data : 239
Processing data : 240
Processing data : 241
Processing data : 242
Processing data : 243
Processing data : 244
Processing data : 245
Processing data : 246
Processing data : 247
Processing data : 248
Processing data : 249
Processing data : 250
Processing data : 251
Processing data : 252
Processing data : 253
Processing data : 254
Processing data : 255
Processing data : 256
Processing data : 257
Processing data : 258
Processing data : 259
Processing data : 260
Processing data : 261
Processing data : 262
Processing data : 263
Processing data : 264
Processing data : 265
Processing data : 266
Processing data : 267
Processing data : 268
Processing data : 269
Processing data : 270
Processing data : 271
Processing data : 272
Processing data : 273
Processing data : 274
Processing data : 275
Processing data : 276
Processing data : 277
Processing data : 278
Processing data : 279
Processing data : 280
Processing data : 281
Processing data : 282
Processing data : 283
Processing data : 284
Processing data : 285
Processing data : 286
Processing data : 287
Processing data : 288
Processing data : 289
Processing data : 290
Processing data : 291
Processing data : 292
Processing data : 293
Processing data : 294
Processing data : 295
Processing data : 296
Processing data : 297
Processing data : 298
Processing data : 299
Processing data : 300
Processing data : 301
Processing data : 302
Processing data : 303
Processing data : 304
Processing data : 305
Processing data : 306
Processing data : 307
Processing data : 308
Processing data : 309
Processing data : 310
Processing data : 311
Processing data : 312
Processing data : 313
Processing data : 314
Processing data : 315
Processing data : 316
Processing data : 317
Processing data : 318
Processing data : 319
Processing data : 320
Processing data : 321
Processing data : 322
Processing data : 323
Processing data : 324
Processing data : 325
Processing data : 326
Processing data : 327
Processing data : 328
Processing data : 329
Processing data : 330
Processing data : 331
Processing data : 332
Processing data : 333
Processing data : 334
Processing data : 335
Processing data : 336
Processing data : 337
Processing data : 338
Processing data : 339
Processing data : 340
Processing data : 341
Processing data : 342
Processing data : 343
Processing data : 344
Processing data : 345
Processing data : 346
Processing data : 347
Processing data : 348
Processing data : 349
Processing data : 350
Processing data : 351
Processing data : 352
Processing data : 353
Processing data : 354
Processing data : 355
Processing data : 356
Processing data : 357
Processing data : 358
Processing data : 359
Processing data : 360
Processing data : 361
Processing data : 362
Processing data : 363
Processing data : 364
Processing data : 365
Processing data : 366
Processing data : 367
Processing data : 368
Processing data : 369
Processing data : 370
Processing data : 371
Processing data : 372
Processing data : 373
Processing data : 374
Processing data : 375
Processing data : 376
Processing data : 377
Processing data : 378
Processing data : 379
Processing data : 380
Processing data : 381
Processing data : 382
Processing data : 383
Processing data : 384
Processing data : 385
Processing data : 386
Processing data : 387
Processing data : 388
Processing data : 389
Processing data : 390
Processing data : 391
Processing data : 392
Processing data : 393
Processing data : 394
Processing data : 395
Processing data : 396
Processing data : 397
Processing data : 398
Processing data : 399
Processing data : 400
Processing data : 401
Processing data : 402
Processing data : 403
Processing data : 404
Processing data : 405
Processing data : 406
Processing data : 407
Processing data : 408
Processing data : 409
Processing data : 410
Processing data : 411
Processing data : 412
Processing data : 413
Processing data : 414
Processing data : 415
Processing data : 416
Processing data : 417
Processing data : 418
Processing data : 419
Processing data : 420
Processing data : 421
Processing data : 422
Processing data : 423
Processing data : 424
Processing data : 425
Processing data : 426
Processing data : 427
Processing data : 428
Processing data : 429
Processing data : 430
Processing data : 431
Processing data : 432
Processing data : 433
Processing data : 434
Processing data : 435
Processing data : 436
Processing data : 437
Processing data : 438
Processing data : 439
Processing data : 440
Processing data : 441
Processing data : 442
Processing data : 443
Processing data : 444
Processing data : 445
Processing data : 446
Processing data : 447
Processing data : 448
Processing data : 449
Processing data : 450
Processing data : 451
Processing data : 452
Processing data : 453
Processing data : 454
Processing data : 455
Processing data : 456
Processing data : 457
Processing data : 458
Processing data : 459
Processing data : 460
Processing data : 461
Processing data : 462
Processing data : 463
Processing data : 464
Processing data : 465
Processing data : 466
Processing data : 467
Processing data : 468
Processing data : 469
Processing data : 470
Processing data : 471
Processing data : 472
Processing data : 473
Processing data : 474
Processing data : 475
Processing data : 476
Processing data : 477
Processing data : 478
Processing data : 479
Processing data : 480
Processing data : 481
Processing data : 482
Processing data : 483
Processing data : 484
Processing data : 485
Processing data : 486
Processing data : 487
Processing data : 488
Processing data : 489
Processing data : 490
Processing data : 491
Processing data : 492
Processing data : 493
Processing data : 494
Processing data : 495
Processing data : 496
Processing data : 497
Processing data : 498
Processing data : 499

In [13]:
#define path for save faiss index
path_faiss = "/content/drive/MyDrive/JCAIEAH-003/Notes and Hands On/Modul 3/Day 10/faiss_index"
#save faiss index
vector_store.save_local(path_faiss)
#create new vector store with saved index
new_vector_store = FAISS.load_local(
    path_faiss, embeddings, allow_dangerous_deserialization=True
)

#Retrieve Data from Vector Database

In [14]:
#try to retrieve data from vector database with similarity_search
results = new_vector_store.similarity_search(
    "Women's Cycling Shorts",
    k=2
)
#show the result
results

[Document(id='4044c0ac52c1ee4b28777417651faf42', metadata={'uniq_id': '4044c0ac52c1ee4b28777417651faf42', 'product_name': "Alisha Solid Women's Cycling Shorts"}, page_content="Key Features of Alisha Solid Women's Cycling Shorts Cotton Lycra White, Black, Red, Black,Specifications of Alisha Solid Women's Cycling Shorts Shorts Details Number of Contents in Sales Package Pack of 4 Fabric Cotton Lycra Type Cycling Shorts General Details Pattern Solid Ideal For Women's Fabric Care Gentle Machine Wash in Lukewarm Water, Do Not Bleach Additional Details Style Code ALTGHT4P_39 In the Box 4 shorts"),
 Document(id='0973b37acd0c664e3de26e97e5571454', metadata={'uniq_id': '0973b37acd0c664e3de26e97e5571454', 'product_name': "Alisha Solid Women's Cycling Shorts"}, page_content="Key Features of Alisha Solid Women's Cycling Shorts Cotton Lycra Black, Red,Specifications of Alisha Solid Women's Cycling Shorts Shorts Details Number of Contents in Sales Package Pack of 2 Fabric Cotton Lycra Type Cycling Shorts General Details Pattern Solid Ideal For Women's Fabric Care Gentle Machine Wash in Lukewarm Water, Do Not Bleach Additional Details Style Code ALTGHT_11 In the Box 2 shorts")]

In [15]:
#parsing page content and metadata for each retrieved document
for res in results:
    print(f"Result Page Content:  {res.page_content}\nResult Metadata: [{res.metadata}]")
    print("-----"*20)

Result Page Content:  Key Features of Alisha Solid Women's Cycling Shorts Cotton Lycra White, Black, Red, Black,Specifications of Alisha Solid Women's Cycling Shorts Shorts Details Number of Contents in Sales Package Pack of 4 Fabric Cotton Lycra Type Cycling Shorts General Details Pattern Solid Ideal For Women's Fabric Care Gentle Machine Wash in Lukewarm Water, Do Not Bleach Additional Details Style Code ALTGHT4P_39 In the Box 4 shorts
Result Metadata: [{'uniq_id': '4044c0ac52c1ee4b28777417651faf42', 'product_name': "Alisha Solid Women's Cycling Shorts"}]
----------------------------------------------------------------------------------------------------
Result Page Content:  Key Features of Alisha Solid Women's Cycling Shorts Cotton Lycra Black, Red,Specifications of Alisha Solid Women's Cycling Shorts Shorts Details Number of Contents in Sales Package Pack of 2 Fabric Cotton Lycra Type Cycling Shorts General Details Pattern Solid Ideal For Women's Fabric Care Gentle Machine Wash in Lukewarm Water, Do Not Bleach Additional Details Style Code ALTGHT_11 In the Box 2 shorts
Result Metadata: [{'uniq_id': '0973b37acd0c664e3de26e97e5571454', 'product_name': "Alisha Solid Women's Cycling Shorts"}]
----------------------------------------------------------------------------------------------------

In [16]:
#try to retrieve data from vector database with similarity_search_with_score
#this method will give you additional information about similarity score
results = new_vector_store.similarity_search_with_score(
    "Women's Cycling Shorts",
    k=2
)
# show the result
results

[(Document(id='4044c0ac52c1ee4b28777417651faf42', metadata={'uniq_id': '4044c0ac52c1ee4b28777417651faf42', 'product_name': "Alisha Solid Women's Cycling Shorts"}, page_content="Key Features of Alisha Solid Women's Cycling Shorts Cotton Lycra White, Black, Red, Black,Specifications of Alisha Solid Women's Cycling Shorts Shorts Details Number of Contents in Sales Package Pack of 4 Fabric Cotton Lycra Type Cycling Shorts General Details Pattern Solid Ideal For Women's Fabric Care Gentle Machine Wash in Lukewarm Water, Do Not Bleach Additional Details Style Code ALTGHT4P_39 In the Box 4 shorts"),
  np.float32(0.7805227)),
 (Document(id='0973b37acd0c664e3de26e97e5571454', metadata={'uniq_id': '0973b37acd0c664e3de26e97e5571454', 'product_name': "Alisha Solid Women's Cycling Shorts"}, page_content="Key Features of Alisha Solid Women's Cycling Shorts Cotton Lycra Black, Red,Specifications of Alisha Solid Women's Cycling Shorts Shorts Details Number of Contents in Sales Package Pack of 2 Fabric Cotton Lycra Type Cycling Shorts General Details Pattern Solid Ideal For Women's Fabric Care Gentle Machine Wash in Lukewarm Water, Do Not Bleach Additional Details Style Code ALTGHT_11 In the Box 2 shorts"),
  np.float32(0.78228253))]

In [17]:
#parsing page content, metadata, and similarity score for each retrieved document
for res,score in results:
    print(f"Score: {score}\nResult Page Content:  {res.page_content}\nResult Metadata: [{res.metadata}]")
    print("-----"*20)

Score: 0.7805227041244507
Result Page Content:  Key Features of Alisha Solid Women's Cycling Shorts Cotton Lycra White, Black, Red, Black,Specifications of Alisha Solid Women's Cycling Shorts Shorts Details Number of Contents in Sales Package Pack of 4 Fabric Cotton Lycra Type Cycling Shorts General Details Pattern Solid Ideal For Women's Fabric Care Gentle Machine Wash in Lukewarm Water, Do Not Bleach Additional Details Style Code ALTGHT4P_39 In the Box 4 shorts
Result Metadata: [{'uniq_id': '4044c0ac52c1ee4b28777417651faf42', 'product_name': "Alisha Solid Women's Cycling Shorts"}]
----------------------------------------------------------------------------------------------------
Score: 0.7822825312614441
Result Page Content:  Key Features of Alisha Solid Women's Cycling Shorts Cotton Lycra Black, Red,Specifications of Alisha Solid Women's Cycling Shorts Shorts Details Number of Contents in Sales Package Pack of 2 Fabric Cotton Lycra Type Cycling Shorts General Details Pattern Solid Ideal For Women's Fabric Care Gentle Machine Wash in Lukewarm Water, Do Not Bleach Additional Details Style Code ALTGHT_11 In the Box 2 shorts
Result Metadata: [{'uniq_id': '0973b37acd0c664e3de26e97e5571454', 'product_name': "Alisha Solid Women's Cycling Shorts"}]
----------------------------------------------------------------------------------------------------

**search_type**: Type of search to perform. Can be “similarity”, “mmr”, or “similarity_score_threshold”.

**search_kwargs**: Keyword arguments to pass to the
search function.  
Can include things like:  
* k: Amount of documents to return (Default: 4) score_threshold: Minimum relevance threshold
* fetch_k: Amount of documents to pass to MMR algorithm
(Default: 20)
* lambda_mult: Diversity of results returned by MMR;
1 for minimum diversity and 0 for maximum. (Default: 0.5)

In [18]:
#retrieve data with non-default search_type.
#basically, default search_type is similarity_score_threshold, the code below shows how to retrieve with another search_type
retriever = new_vector_store.as_retriever(search_type="mmr", search_kwargs={"k": 1})
retriever.invoke("Women's Cycling Shorts")

[Document(id='4044c0ac52c1ee4b28777417651faf42', metadata={'uniq_id': '4044c0ac52c1ee4b28777417651faf42', 'product_name': "Alisha Solid Women's Cycling Shorts"}, page_content="Key Features of Alisha Solid Women's Cycling Shorts Cotton Lycra White, Black, Red, Black,Specifications of Alisha Solid Women's Cycling Shorts Shorts Details Number of Contents in Sales Package Pack of 4 Fabric Cotton Lycra Type Cycling Shorts General Details Pattern Solid Ideal For Women's Fabric Care Gentle Machine Wash in Lukewarm Water, Do Not Bleach Additional Details Style Code ALTGHT4P_39 In the Box 4 shorts")]