In [1]:
import mysql.connector
import pandas as pd

In [ ]:
# build connection to DB
myDB = mysql.connector.connect(
    host = 'localhost',
    user = 'root',
    passwd = 'admin123',
    database = 'world'
)

In [ ]:
# create access to DB
mycursor = myDB.cursor()

# write query
query = "select * from city"

# execute query
mycursor.execute(query)

# save output in result variable
result = mycursor.fetchall()

In [6]:
result

[(1, 'Kabul', 'AFG', 'Kabol', 1780000),
 (2, 'Qandahar', 'AFG', 'Qandahar', 237500),
 (3, 'Herat', 'AFG', 'Herat', 186800),
 (4, 'Mazar-e-Sharif', 'AFG', 'Balkh', 127800),
 (5, 'Amsterdam', 'NLD', 'Noord-Holland', 731200),
 (6, 'Rotterdam', 'NLD', 'Zuid-Holland', 593321),
 (7, 'Haag', 'NLD', 'Zuid-Holland', 440900),
 (8, 'Utrecht', 'NLD', 'Utrecht', 234323),
 (9, 'Eindhoven', 'NLD', 'Noord-Brabant', 201843),
 (10, 'Tilburg', 'NLD', 'Noord-Brabant', 193238),
 (11, 'Groningen', 'NLD', 'Groningen', 172701),
 (12, 'Breda', 'NLD', 'Noord-Brabant', 160398),
 (13, 'Apeldoorn', 'NLD', 'Gelderland', 153491),
 (14, 'Nijmegen', 'NLD', 'Gelderland', 152463),
 (15, 'Enschede', 'NLD', 'Overijssel', 149544),
 (16, 'Haarlem', 'NLD', 'Noord-Holland', 148772),
 (17, 'Almere', 'NLD', 'Flevoland', 142465),
 (18, 'Arnhem', 'NLD', 'Gelderland', 138020),
 (19, 'Zaanstad', 'NLD', 'Noord-Holland', 135621),
 (20, '´s-Hertogenbosch', 'NLD', 'Noord-Brabant', 129170),
 (21, 'Amersfoort', 'NLD', 'Utrecht', 126270),
 (22, 'Maastricht', 'NLD', 'Limburg', 122087),
 (23, 'Dordrecht', 'NLD', 'Zuid-Holland', 119811),
 (24, 'Leiden', 'NLD', 'Zuid-Holland', 117196),
 (25, 'Haarlemmermeer', 'NLD', 'Noord-Holland', 110722),
 (26, 'Zoetermeer', 'NLD', 'Zuid-Holland', 110214),
 (27, 'Emmen', 'NLD', 'Drenthe', 105853),
 (28, 'Zwolle', 'NLD', 'Overijssel', 105819),
 (29, 'Ede', 'NLD', 'Gelderland', 101574),
 (30, 'Delft', 'NLD', 'Zuid-Holland', 95268),
 (31, 'Heerlen', 'NLD', 'Limburg', 95052),
 (32, 'Alkmaar', 'NLD', 'Noord-Holland', 92713),
 (33, 'Willemstad', 'ANT', 'Curaçao', 2345),
 (34, 'Tirana', 'ALB', 'Tirana', 270000),
 (35, 'Alger', 'DZA', 'Alger', 2168000),
 (36, 'Oran', 'DZA', 'Oran', 609823),
 (37, 'Constantine', 'DZA', 'Constantine', 443727),
 (38, 'Annaba', 'DZA', 'Annaba', 222518),
 (39, 'Batna', 'DZA', 'Batna', 183377),
 (40, 'Sétif', 'DZA', 'Sétif', 179055),
 (41, 'Sidi Bel Abbès', 'DZA', 'Sidi Bel Abbès', 153106),
 (42, 'Skikda', 'DZA', 'Skikda', 128747),
 (43, 'Biskra', 'DZA', 'Biskra', 128281),
 (44, 'Blida (el-Boulaida)', 'DZA', 'Blida', 127284),
 (45, 'Béjaïa', 'DZA', 'Béjaïa', 117162),
 (46, 'Mostaganem', 'DZA', 'Mostaganem', 115212),
 (47, 'Tébessa', 'DZA', 'Tébessa', 112007),
 (48, 'Tlemcen (Tilimsen)', 'DZA', 'Tlemcen', 110242),
 (49, 'Béchar', 'DZA', 'Béchar', 107311),
 (50, 'Tiaret', 'DZA', 'Tiaret', 100118),
 (51, 'Ech-Chleff (el-Asnam)', 'DZA', 'Chlef', 96794),
 (52, 'Ghardaïa', 'DZA', 'Ghardaïa', 89415),
 (53, 'Tafuna', 'ASM', 'Tutuila', 5200),
 (54, 'Fagatogo', 'ASM', 'Tutuila', 2323),
 (55, 'Andorra la Vella', 'AND', 'Andorra la Vella', 21189),
 (56, 'Luanda', 'AGO', 'Luanda', 2022000),
 (57, 'Huambo', 'AGO', 'Huambo', 163100),
 (58, 'Lobito', 'AGO', 'Benguela', 130000),
 (59, 'Benguela', 'AGO', 'Benguela', 128300),
 (60, 'Namibe', 'AGO', 'Namibe', 118200),
 (61, 'South Hill', 'AIA', '–', 961),
 (62, 'The Valley', 'AIA', '–', 595),
 (63, 'Saint John´s', 'ATG', 'St John', 24000),
 (64, 'Dubai', 'ARE', 'Dubai', 669181),
 (65, 'Abu Dhabi', 'ARE', 'Abu Dhabi', 398695),
 (66, 'Sharja', 'ARE', 'Sharja', 320095),
 (67, 'al-Ayn', 'ARE', 'Abu Dhabi', 225970),
 (68, 'Ajman', 'ARE', 'Ajman', 114395),
 (69, 'Buenos Aires', 'ARG', 'Distrito Federal', 2982146),
 (70, 'La Matanza', 'ARG', 'Buenos Aires', 1266461),
 (71, 'Córdoba', 'ARG', 'Córdoba', 1157507),
 (72, 'Rosario', 'ARG', 'Santa Fé', 907718),
 (73, 'Lomas de Zamora', 'ARG', 'Buenos Aires', 622013),
 (74, 'Quilmes', 'ARG', 'Buenos Aires', 559249),
 (75, 'Almirante Brown', 'ARG', 'Buenos Aires', 538918),
 (76, 'La Plata', 'ARG', 'Buenos Aires', 521936),
 (77, 'Mar del Plata', 'ARG', 'Buenos Aires', 512880),
 (78, 'San Miguel de Tucumán', 'ARG', 'Tucumán', 470809),
 (79, 'Lanús', 'ARG', 'Buenos Aires', 469735),
 (80, 'Merlo', 'ARG', 'Buenos Aires', 463846),
 (81, 'General San Martín', 'ARG', 'Buenos Aires', 422542),
 (82, 'Salta', 'ARG', 'Salta', 367550),
 (83, 'Moreno', 'ARG', 'Buenos Aires', 356993),
 (84, 'Santa Fé', 'ARG', 'Santa Fé', 353063),
 (85, 'Avellaneda', 'ARG', 'Buenos Aires', 353046),
 (86, 'Tres de Febrero', 'ARG', 'Buenos Aires', 352311),
 (87, 'Morón', 'ARG', 'Buenos Aires', 349246),
 (88, 'Florencio Varela', 'ARG', 'Buenos Aires', 315432),
 (89, 'San Isidro', 'ARG', 'Buenos Aires', 306341),
 (90, 'Tigre', 'ARG', 'Buenos Aires', 296226),
 (91, 'Malvinas Argentinas', 'ARG', 'Buenos Aires', 290335),
 (92, 'Vicente López', 'ARG', 'Buenos Aires', 288341),
 (93, 'Berazategui', 'ARG', 'Buenos Aires', 276916),
 (94, 'Corrientes', 'ARG', 'Corrientes', 258103),
 (95, 'San Miguel', 'ARG', 'Buenos Aires', 248700),
 (96, 'Bahía Blanca', 'ARG', 'Buenos Aires', 239810),
 (97, 'Esteban Echeverría', 'ARG', 'Buenos Aires', 235760),
 (98, 'Resistencia', 'ARG', 'Chaco', 229212),
 (99, 'José C. Paz', 'ARG', 'Buenos Aires', 221754),
 (100, 'Paraná', 'ARG', 'Entre Rios', 207041),
 (101, 'Godoy Cruz', 'ARG', 'Mendoza', 206998),
 (102, 'Posadas', 'ARG', 'Misiones', 201273),
 (103, 'Guaymallén', 'ARG', 'Mendoza', 200595),
 (104, 'Santiago del Estero', 'ARG', 'Santiago del Estero', 189947),
 (105, 'San Salvador de Jujuy', 'ARG', 'Jujuy', 178748),
 (106, 'Hurlingham', 'ARG', 'Buenos Aires', 170028),
 (107, 'Neuquén', 'ARG', 'Neuquén', 167296),
 (108, 'Ituzaingó', 'ARG', 'Buenos Aires', 158197),
 (109, 'San Fernando', 'ARG', 'Buenos Aires', 153036),
 (110, 'Formosa', 'ARG', 'Formosa', 147636),
 (111, 'Las Heras', 'ARG', 'Mendoza', 145823),
 (112, 'La Rioja', 'ARG', 'La Rioja', 138117),
 (113, 'San Fernando del Valle de Cata', 'ARG', 'Catamarca', 134935),
 (114, 'Río Cuarto', 'ARG', 'Córdoba', 134355),
 (115, 'Comodoro Rivadavia', 'ARG', 'Chubut', 124104),
 (116, 'Mendoza', 'ARG', 'Mendoza', 123027),
 (117, 'San Nicolás de los Arroyos', 'ARG', 'Buenos Aires', 119302),
 (118, 'San Juan', 'ARG', 'San Juan', 119152),
 (119, 'Escobar', 'ARG', 'Buenos Aires', 116675),
 (120, 'Concordia', 'ARG', 'Entre Rios', 116485),
 (121, 'Pilar', 'ARG', 'Buenos Aires', 113428),
 (122, 'San Luis', 'ARG', 'San Luis', 110136),
 (123, 'Ezeiza', 'ARG', 'Buenos Aires', 99578),
 (124, 'San Rafael', 'ARG', 'Mendoza', 94651),
 (125, 'Tandil', 'ARG', 'Buenos Aires', 91101),
 (126, 'Yerevan', 'ARM', 'Yerevan', 1248700),
 (127, 'Gjumri', 'ARM', 'Širak', 211700),
 (128, 'Vanadzor', 'ARM', 'Lori', 172700),
 (129, 'Oranjestad', 'ABW', '–', 29034),
 (130, 'Sydney', 'AUS', 'New South Wales', 3276207),
 (131, 'Melbourne', 'AUS', 'Victoria', 2865329),
 (132, 'Brisbane', 'AUS', 'Queensland', 1291117),
 (133, 'Perth', 'AUS', 'West Australia', 1096829),
 (134, 'Adelaide', 'AUS', 'South Australia', 978100),
 (135, 'Canberra', 'AUS', 'Capital Region', 322723),
 (136, 'Gold Coast', 'AUS', 'Queensland', 311932),
 (137, 'Newcastle', 'AUS', 'New South Wales', 270324),
 (138, 'Central Coast', 'AUS', 'New South Wales', 227657),
 (139, 'Wollongong', 'AUS', 'New South Wales', 219761),
 (140, 'Hobart', 'AUS', 'Tasmania', 126118),
 (141, 'Geelong', 'AUS', 'Victoria', 125382),
 (142, 'Townsville', 'AUS', 'Queensland', 109914),
 (143, 'Cairns', 'AUS', 'Queensland', 92273),
 (144, 'Baku', 'AZE', 'Baki', 1787800),
 (145, 'Gäncä', 'AZE', 'Gäncä', 299300),
 (146, 'Sumqayit', 'AZE', 'Sumqayit', 283000),
 (147, 'Mingäçevir', 'AZE', 'Mingäçevir', 93900),
 (148, 'Nassau', 'BHS', 'New Providence', 172000),
 (149, 'al-Manama', 'BHR', 'al-Manama', 148000),
 (150, 'Dhaka', 'BGD', 'Dhaka', 3612850),
 (151, 'Chittagong', 'BGD', 'Chittagong', 1392860),
 (152, 'Khulna', 'BGD', 'Khulna', 663340),
 (153, 'Rajshahi', 'BGD', 'Rajshahi', 294056),
 (154, 'Narayanganj', 'BGD', 'Dhaka', 202134),
 (155, 'Rangpur', 'BGD', 'Rajshahi', 191398),
 (156, 'Mymensingh', 'BGD', 'Dhaka', 188713),
 (157, 'Barisal', 'BGD', 'Barisal', 170232),
 (158, 'Tungi', 'BGD', 'Dhaka', 168702),
 (159, 'Jessore', 'BGD', 'Khulna', 139710),
 (160, 'Comilla', 'BGD', 'Chittagong', 135313),
 (161, 'Nawabganj', 'BGD', 'Rajshahi', 130577),
 (162, 'Dinajpur', 'BGD', 'Rajshahi', 127815),
 (163, 'Bogra', 'BGD', 'Rajshahi', 120170),
 (164, 'Sylhet', 'BGD', 'Sylhet', 117396),
 (165, 'Brahmanbaria', 'BGD', 'Chittagong', 109032),
 (166, 'Tangail', 'BGD', 'Dhaka', 106004),
 (167, 'Jamalpur', 'BGD', 'Dhaka', 103556),
 (168, 'Pabna', 'BGD', 'Rajshahi', 103277),
 (169, 'Naogaon', 'BGD', 'Rajshahi', 101266),
 (170, 'Sirajganj', 'BGD', 'Rajshahi', 99669),
 (171, 'Narsinghdi', 'BGD', 'Dhaka', 98342),
 (172, 'Saidpur', 'BGD', 'Rajshahi', 96777),
 (173, 'Gazipur', 'BGD', 'Dhaka', 96717),
 (174, 'Bridgetown', 'BRB', 'St Michael', 6070),
 (175, 'Antwerpen', 'BEL', 'Antwerpen', 446525),
 (176, 'Gent', 'BEL', 'East Flanderi', 224180),
 (177, 'Charleroi', 'BEL', 'Hainaut', 200827),
 (178, 'Liège', 'BEL', 'Liège', 185639),
 (179, 'Bruxelles [Brussel]', 'BEL', 'Bryssel', 133859),
 (180, 'Brugge', 'BEL', 'West Flanderi', 116246),
 (181, 'Schaerbeek', 'BEL', 'Bryssel', 105692),
 (182, 'Namur', 'BEL', 'Namur', 105419),
 (183, 'Mons', 'BEL', 'Hainaut', 90935),
 (184, 'Belize City', 'BLZ', 'Belize City', 55810),
 (185, 'Belmopan', 'BLZ', 'Cayo', 7105),
 (186, 'Cotonou', 'BEN', 'Atlantique', 536827),
 (187, 'Porto-Novo', 'BEN', 'Ouémé', 194000),
 (188, 'Djougou', 'BEN', 'Atacora', 134099),
 (189, 'Parakou', 'BEN', 'Borgou', 103577),
 (190, 'Saint George', 'BMU', 'Saint George´s', 1800),
 (191, 'Hamilton', 'BMU', 'Hamilton', 1200),
 (192, 'Thimphu', 'BTN', 'Thimphu', 22000),
 (193, 'Santa Cruz de la Sierra', 'BOL', 'Santa Cruz', 935361),
 (194, 'La Paz', 'BOL', 'La Paz', 758141),
 (195, 'El Alto', 'BOL', 'La Paz', 534466),
 (196, 'Cochabamba', 'BOL', 'Cochabamba', 482800),
 (197, 'Oruro', 'BOL', 'Oruro', 223553),
 (198, 'Sucre', 'BOL', 'Chuquisaca', 178426),
 (199, 'Potosí', 'BOL', 'Potosí', 140642),
 (200, 'Tarija', 'BOL', 'Tarija', 125255),
 (201, 'Sarajevo', 'BIH', 'Federaatio', 360000),
 (202, 'Banja Luka', 'BIH', 'Republika Srpska', 143079),
 (203, 'Zenica', 'BIH', 'Federaatio', 96027),
 (204, 'Gaborone', 'BWA', 'Gaborone', 213017),
 (205, 'Francistown', 'BWA', 'Francistown', 101805),
 (206, 'São Paulo', 'BRA', 'São Paulo', 9968485),
 (207, 'Rio de Janeiro', 'BRA', 'Rio de Janeiro', 5598953),
 (208, 'Salvador', 'BRA', 'Bahia', 2302832),
 (209, 'Belo Horizonte', 'BRA', 'Minas Gerais', 2139125),
 (210, 'Fortaleza', 'BRA', 'Ceará', 2097757),
 (211, 'Brasília', 'BRA', 'Distrito Federal', 1969868),
 (212, 'Curitiba', 'BRA', 'Paraná', 1584232),
 (213, 'Recife', 'BRA', 'Pernambuco', 1378087),
 (214, 'Porto Alegre', 'BRA', 'Rio Grande do Sul', 1314032),
 (215, 'Manaus', 'BRA', 'Amazonas', 1255049),
 (216, 'Belém', 'BRA', 'Pará', 1186926),
 (217, 'Guarulhos', 'BRA', 'São Paulo', 1095874),
 (218, 'Goiânia', 'BRA', 'Goiás', 1056330),
 (219, 'Campinas', 'BRA', 'São Paulo', 950043),
 (220, 'São Gonçalo', 'BRA', 'Rio de Janeiro', 869254),
 (221, 'Nova Iguaçu', 'BRA', 'Rio de Janeiro', 862225),
 (222, 'São Luís', 'BRA', 'Maranhão', 837588),
 (223, 'Maceió', 'BRA', 'Alagoas', 786288),
 (224, 'Duque de Caxias', 'BRA', 'Rio de Janeiro', 746758),
 (225, 'São Bernardo do Campo', 'BRA', 'São Paulo', 723132),
 (226, 'Teresina', 'BRA', 'Piauí', 691942),
 (227, 'Natal', 'BRA', 'Rio Grande do Norte', 688955),
 (228, 'Osasco', 'BRA', 'São Paulo', 659604),
 (229, 'Campo Grande', 'BRA', 'Mato Grosso do Sul', 649593),
 (230, 'Santo André', 'BRA', 'São Paulo', 630073),
 (231, 'João Pessoa', 'BRA', 'Paraíba', 584029),
 (232, 'Jaboatão dos Guararapes', 'BRA', 'Pernambuco', 558680),
 (233, 'Contagem', 'BRA', 'Minas Gerais', 520801),
 (234, 'São José dos Campos', 'BRA', 'São Paulo', 515553),
 (235, 'Uberlândia', 'BRA', 'Minas Gerais', 487222),
 (236, 'Feira de Santana', 'BRA', 'Bahia', 479992),
 (237, 'Ribeirão Preto', 'BRA', 'São Paulo', 473276),
 (238, 'Sorocaba', 'BRA', 'São Paulo', 466823),
 (239, 'Niterói', 'BRA', 'Rio de Janeiro', 459884),
 (240, 'Cuiabá', 'BRA', 'Mato Grosso', 453813),
 (241, 'Juiz de Fora', 'BRA', 'Minas Gerais', 450288),
 (242, 'Aracaju', 'BRA', 'Sergipe', 445555),
 (243, 'São João de Meriti', 'BRA', 'Rio de Janeiro', 440052),
 (244, 'Londrina', 'BRA', 'Paraná', 432257),
 (245, 'Joinville', 'BRA', 'Santa Catarina', 428011),
 (246, 'Belford Roxo', 'BRA', 'Rio de Janeiro', 425194),
 (247, 'Santos', 'BRA', 'São Paulo', 408748),
 (248, 'Ananindeua', 'BRA', 'Pará', 400940),
 (249, 'Campos dos Goytacazes', 'BRA', 'Rio de Janeiro', 398418),
 (250, 'Mauá', 'BRA', 'São Paulo', 375055),
 (251, 'Carapicuíba', 'BRA', 'São Paulo', 357552),
 (252, 'Olinda', 'BRA', 'Pernambuco', 354732),
 (253, 'Campina Grande', 'BRA', 'Paraíba', 352497),
 (254, 'São José do Rio Preto', 'BRA', 'São Paulo', 351944),
 (255, 'Caxias do Sul', 'BRA', 'Rio Grande do Sul', 349581),
 (256, 'Moji das Cruzes', 'BRA', 'São Paulo', 339194),
 (257, 'Diadema', 'BRA', 'São Paulo', 335078),
 (258, 'Aparecida de Goiânia', 'BRA', 'Goiás', 324662),
 (259, 'Piracicaba', 'BRA', 'São Paulo', 319104),
 (260, 'Cariacica', 'BRA', 'Espírito Santo', 319033),
 (261, 'Vila Velha', 'BRA', 'Espírito Santo', 318758),
 (262, 'Pelotas', 'BRA', 'Rio Grande do Sul', 315415),
 (263, 'Bauru', 'BRA', 'São Paulo', 313670),
 (264, 'Porto Velho', 'BRA', 'Rondônia', 309750),
 (265, 'Serra', 'BRA', 'Espírito Santo', 302666),
 (266, 'Betim', 'BRA', 'Minas Gerais', 302108),
 (267, 'Jundíaí', 'BRA', 'São Paulo', 296127),
 (268, 'Canoas', 'BRA', 'Rio Grande do Sul', 294125),
 (269, 'Franca', 'BRA', 'São Paulo', 290139),
 (270, 'São Vicente', 'BRA', 'São Paulo', 286848),
 (271, 'Maringá', 'BRA', 'Paraná', 286461),
 (272, 'Montes Claros', 'BRA', 'Minas Gerais', 286058),
 (273, 'Anápolis', 'BRA', 'Goiás', 282197),
 (274, 'Florianópolis', 'BRA', 'Santa Catarina', 281928),
 (275, 'Petrópolis', 'BRA', 'Rio de Janeiro', 279183),
 (276, 'Itaquaquecetuba', 'BRA', 'São Paulo', 270874),
 (277, 'Vitória', 'BRA', 'Espírito Santo', 270626),
 (278, 'Ponta Grossa', 'BRA', 'Paraná', 268013),
 (279, 'Rio Branco', 'BRA', 'Acre', 259537),
 (280, 'Foz do Iguaçu', 'BRA', 'Paraná', 259425),
 (281, 'Macapá', 'BRA', 'Amapá', 256033),
 (282, 'Ilhéus', 'BRA', 'Bahia', 254970),
 (283, 'Vitória da Conquista', 'BRA', 'Bahia', 253587),
 (284, 'Uberaba', 'BRA', 'Minas Gerais', 249225),
 (285, 'Paulista', 'BRA', 'Pernambuco', 248473),
 (286, 'Limeira', 'BRA', 'São Paulo', 245497),
 (287, 'Blumenau', 'BRA', 'Santa Catarina', 244379),
 (288, 'Caruaru', 'BRA', 'Pernambuco', 244247),
 (289, 'Santarém', 'BRA', 'Pará', 241771),
 (290, 'Volta Redonda', 'BRA', 'Rio de Janeiro', 240315),
 (291, 'Novo Hamburgo', 'BRA', 'Rio Grande do Sul', 239940),
 (292, 'Caucaia', 'BRA', 'Ceará', 238738),
 (293, 'Santa Maria', 'BRA', 'Rio Grande do Sul', 238473),
 (294, 'Cascavel', 'BRA', 'Paraná', 237510),
 (295, 'Guarujá', 'BRA', 'São Paulo', 237206),
 (296, 'Ribeirão das Neves', 'BRA', 'Minas Gerais', 232685),
 (297, 'Governador Valadares', 'BRA', 'Minas Gerais', 231724),
 (298, 'Taubaté', 'BRA', 'São Paulo', 229130),
 (299, 'Imperatriz', 'BRA', 'Maranhão', 224564),
 (300, 'Gravataí', 'BRA', 'Rio Grande do Sul', 223011),
 (301, 'Embu', 'BRA', 'São Paulo', 222223),
 (302, 'Mossoró', 'BRA', 'Rio Grande do Norte', 214901),
 (303, 'Várzea Grande', 'BRA', 'Mato Grosso', 214435),
 (304, 'Petrolina', 'BRA', 'Pernambuco', 210540),
 (305, 'Barueri', 'BRA', 'São Paulo', 208426),
 (306, 'Viamão', 'BRA', 'Rio Grande do Sul', 207557),
 (307, 'Ipatinga', 'BRA', 'Minas Gerais', 206338),
 (308, 'Juazeiro', 'BRA', 'Bahia', 201073),
 (309, 'Juazeiro do Norte', 'BRA', 'Ceará', 199636),
 (310, 'Taboão da Serra', 'BRA', 'São Paulo', 197550),
 (311, 'São José dos Pinhais', 'BRA', 'Paraná', 196884),
 (312, 'Magé', 'BRA', 'Rio de Janeiro', 196147),
 (313, 'Suzano', 'BRA', 'São Paulo', 195434),
 (314, 'São Leopoldo', 'BRA', 'Rio Grande do Sul', 189258),
 (315, 'Marília', 'BRA', 'São Paulo', 188691),
 (316, 'São Carlos', 'BRA', 'São Paulo', 187122),
 (317, 'Sumaré', 'BRA', 'São Paulo', 186205),
 (318, 'Presidente Prudente', 'BRA', 'São Paulo', 185340),
 (319, 'Divinópolis', 'BRA', 'Minas Gerais', 185047),
 (320, 'Sete Lagoas', 'BRA', 'Minas Gerais', 182984),
 (321, 'Rio Grande', 'BRA', 'Rio Grande do Sul', 182222),
 (322, 'Itabuna', 'BRA', 'Bahia', 182148),
 (323, 'Jequié', 'BRA', 'Bahia', 179128),
 (324, 'Arapiraca', 'BRA', 'Alagoas', 178988),
 (325, 'Colombo', 'BRA', 'Paraná', 177764),
 (326, 'Americana', 'BRA', 'São Paulo', 177409),
 (327, 'Alvorada', 'BRA', 'Rio Grande do Sul', 175574),
 (328, 'Araraquara', 'BRA', 'São Paulo', 174381),
 (329, 'Itaboraí', 'BRA', 'Rio de Janeiro', 173977),
 (330, 'Santa Bárbara d´Oeste', 'BRA', 'São Paulo', 171657),
 (331, 'Nova Friburgo', 'BRA', 'Rio de Janeiro', 170697),
 (332, 'Jacareí', 'BRA', 'São Paulo', 170356),
 (333, 'Araçatuba', 'BRA', 'São Paulo', 169303),
 (334, 'Barra Mansa', 'BRA', 'Rio de Janeiro', 168953),
 (335, 'Praia Grande', 'BRA', 'São Paulo', 168434),
 (336, 'Marabá', 'BRA', 'Pará', 167795),
 (337, 'Criciúma', 'BRA', 'Santa Catarina', 167661),
 (338, 'Boa Vista', 'BRA', 'Roraima', 167185),
 (339, 'Passo Fundo', 'BRA', 'Rio Grande do Sul', 166343),
 (340, 'Dourados', 'BRA', 'Mato Grosso do Sul', 164716),
 (341, 'Santa Luzia', 'BRA', 'Minas Gerais', 164704),
 (342, 'Rio Claro', 'BRA', 'São Paulo', 163551),
 (343, 'Maracanaú', 'BRA', 'Ceará', 162022),
 (344, 'Guarapuava', 'BRA', 'Paraná', 160510),
 (345, 'Rondonópolis', 'BRA', 'Mato Grosso', 155115),
 (346, 'São José', 'BRA', 'Santa Catarina', 155105),
 (347, 'Cachoeiro de Itapemirim', 'BRA', 'Espírito Santo', 155024),
 (348, 'Nilópolis', 'BRA', 'Rio de Janeiro', 153383),
 (349, 'Itapevi', 'BRA', 'São Paulo', 150664),
 (350, 'Cabo de Santo Agostinho', 'BRA', 'Pernambuco', 149964),
 (351, 'Camaçari', 'BRA', 'Bahia', 149146),
 (352, 'Sobral', 'BRA', 'Ceará', 146005),
 (353, 'Itajaí', 'BRA', 'Santa Catarina', 145197),
 (354, 'Chapecó', 'BRA', 'Santa Catarina', 144158),
 (355, 'Cotia', 'BRA', 'São Paulo', 140042),
 (356, 'Lages', 'BRA', 'Santa Catarina', 139570),
 (357, 'Ferraz de Vasconcelos', 'BRA', 'São Paulo', 139283),
 (358, 'Indaiatuba', 'BRA', 'São Paulo', 135968),
 (359, 'Hortolândia', 'BRA', 'São Paulo', 135755),
 (360, 'Caxias', 'BRA', 'Maranhão', 133980),
 (361, 'São Caetano do Sul', 'BRA', 'São Paulo', 133321),
 (362, 'Itu', 'BRA', 'São Paulo', 132736),
 (363, 'Nossa Senhora do Socorro', 'BRA', 'Sergipe', 131351),
 (364, 'Parnaíba', 'BRA', 'Piauí', 129756),
 (365, 'Poços de Caldas', 'BRA', 'Minas Gerais', 129683),
 (366, 'Teresópolis', 'BRA', 'Rio de Janeiro', 128079),
 (367, 'Barreiras', 'BRA', 'Bahia', 127801),
 (368, 'Castanhal', 'BRA', 'Pará', 127634),
 (369, 'Alagoinhas', 'BRA', 'Bahia', 126820),
 (370, 'Itapecerica da Serra', 'BRA', 'São Paulo', 126672),
 (371, 'Uruguaiana', 'BRA', 'Rio Grande do Sul', 126305),
 (372, 'Paranaguá', 'BRA', 'Paraná', 126076),
 (373, 'Ibirité', 'BRA', 'Minas Gerais', 125982),
 (374, 'Timon', 'BRA', 'Maranhão', 125812),
 (375, 'Luziânia', 'BRA', 'Goiás', 125597),
 (376, 'Macaé', 'BRA', 'Rio de Janeiro', 125597),
 (377, 'Teófilo Otoni', 'BRA', 'Minas Gerais', 124489),
 (378, 'Moji-Guaçu', 'BRA', 'São Paulo', 123782),
 (379, 'Palmas', 'BRA', 'Tocantins', 121919),
 (380, 'Pindamonhangaba', 'BRA', 'São Paulo', 121904),
 (381, 'Francisco Morato', 'BRA', 'São Paulo', 121197),
 (382, 'Bagé', 'BRA', 'Rio Grande do Sul', 120793),
 (383, 'Sapucaia do Sul', 'BRA', 'Rio Grande do Sul', 120217),
 (384, 'Cabo Frio', 'BRA', 'Rio de Janeiro', 119503),
 (385, 'Itapetininga', 'BRA', 'São Paulo', 119391),
 (386, 'Patos de Minas', 'BRA', 'Minas Gerais', 119262),
 (387, 'Camaragibe', 'BRA', 'Pernambuco', 118968),
 (388, 'Bragança Paulista', 'BRA', 'São Paulo', 116929),
 (389, 'Queimados', 'BRA', 'Rio de Janeiro', 115020),
 (390, 'Araguaína', 'BRA', 'Tocantins', 114948),
 (391, 'Garanhuns', 'BRA', 'Pernambuco', 114603),
 (392, 'Vitória de Santo Antão', 'BRA', 'Pernambuco', 113595),
 (393, 'Santa Rita', 'BRA', 'Paraíba', 113135),
 (394, 'Barbacena', 'BRA', 'Minas Gerais', 113079),
 (395, 'Abaetetuba', 'BRA', 'Pará', 111258),
 (396, 'Jaú', 'BRA', 'São Paulo', 109965),
 (397, 'Lauro de Freitas', 'BRA', 'Bahia', 109236),
 (398, 'Franco da Rocha', 'BRA', 'São Paulo', 108964),
 (399, 'Teixeira de Freitas', 'BRA', 'Bahia', 108441),
 (400, 'Varginha', 'BRA', 'Minas Gerais', 108314),
 (401, 'Ribeirão Pires', 'BRA', 'São Paulo', 108121),

In [7]:
# convert data to table
df = pd.DataFrame(result, columns=mycursor.column_names)
df

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [8]:
df.head()

   ID            Name CountryCode       District  Population
0   1           Kabul         AFG          Kabol     1780000
1   2        Qandahar         AFG       Qandahar      237500
2   3           Herat         AFG          Herat      186800
3   4  Mazar-e-Sharif         AFG          Balkh      127800
4   5       Amsterdam         NLD  Noord-Holland      731200