# Pandas Merge, Join, and Concat

In [1]:
import pandas as pd
import numpy as np

In [2]:
left_data = {
    'key' : ['K0', 'K1', 'K2', 'K3'],
    'A' : ['A0', 'A1', 'A2', 'A3'],
    'B' : ['B0', 'B1', 'B2', 'B3']
}

right_data = {
    'key' : ['K0', 'K1', 'K3', 'K4'],
    'C' : ['C0', 'C1', 'C3', 'C4'],
    'D' : ['D0', 'D1', 'D3', 'D4']
}

In [3]:
left = pd.DataFrame(left_data)
right = pd.DataFrame(right_data)

In [4]:
left

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [5]:
right

  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K3  C3  D3
3  K4  C4  D4

## Merge

In [6]:
# inner
pd.merge(left, right, on='key')

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K3  A3  B3  C3  D3

In [7]:
# outter
pd.merge(left, right, on='key', how='outer')

  key    A    B    C    D
0  K0   A0   B0   C0   D0
1  K1   A1   B1   C1   D1
2  K2   A2   B2  NaN  NaN
3  K3   A3   B3   C3   D3
4  K4  NaN  NaN   C4   D4

In [8]:
# left
pd.merge(left, right, on='key', how='left')

  key   A   B    C    D
0  K0  A0  B0   C0   D0
1  K1  A1  B1   C1   D1
2  K2  A2  B2  NaN  NaN
3  K3  A3  B3   C3   D3

In [9]:
# right
pd.merge(left, right, on='key', how='right')

  key    A    B   C   D
0  K0   A0   B0  C0  D0
1  K1   A1   B1  C1  D1
2  K3   A3   B3  C3  D3
3  K4  NaN  NaN  C4  D4

## Join

In [17]:
right.set_index('key', inplace=True)
left.set_index('key', inplace=True)

In [19]:
left

      A   B
key
K0   A0  B0
K1   A1  B1
K2   A2  B2
K3   A3  B3

In [20]:
right

      C   D
key
K0   C0  D0
K1   C1  D1
K3   C3  D3
K4   C4  D4

In [21]:
left.join(right, how='inner')

      A   B   C   D
key
K0   A0  B0  C0  D0
K1   A1  B1  C1  D1
K3   A3  B3  C3  D3

In [22]:
left.join(right, how='outer')

       A    B    C    D
key
K0    A0   B0   C0   D0
K1    A1   B1   C1   D1
K2    A2   B2  NaN  NaN
K3    A3   B3   C3   D3
K4   NaN  NaN   C4   D4

In [23]:
left.join(right, how='left')

      A   B    C    D
key
K0   A0  B0   C0   D0
K1   A1  B1   C1   D1
K2   A2  B2  NaN  NaN
K3   A3  B3   C3   D3

In [24]:
left.join(right, how='right')

       A    B   C   D
key
K0    A0   B0  C0  D0
K1    A1   B1  C1  D1
K3    A3   B3  C3  D3
K4   NaN  NaN  C4  D4

## Concat

In [29]:
data1 = {
    'Nama': ['A', 'B', 'C', 'D'],
    'Usia': [10, 11, 12, 13],
    'Berat': [30, 31, 32, 33],
    'Tinggi': [40, 41, 42, 43]
}

data2 = {
    'Nama': ['E', 'F', 'G', 'H'],
    'Usia': [14, 15, 16, 17],
    'Berat': [34, 35, 36, 37],
    'Tinggi': [44, 45, 46, 47]
}

data3 = {
    'Nama': ['I', 'J', 'K', 'L'],
    'Usia': [18, 19, 20, 21],
    'Berat': [38, 39, 40, 41],
    'Tinggi': [48, 49, 50, 51]
}

In [30]:
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
df3 = pd.DataFrame(data3)

In [31]:
pd.concat([df1, df2, df3])

  Nama  Usia  Berat  Tinggi
0    A    10     30      40
1    B    11     31      41
2    C    12     32      42
3    D    13     33      43
0    E    14     34      44
1    F    15     35      45
2    G    16     36      46
3    H    17     37      47
0    I    18     38      48
1    J    19     39      49
2    K    20     40      50
3    L    21     41      51

In [32]:
pd.concat([df1, df2, df3], axis=1)

,Nama,Usia,Berat,Tinggi,Nama,Usia,Berat,Tinggi,Nama,Usia,Berat,Tinggi
0,A,10,30,40,E,14,34,44,I,18,38,48
1,B,11,31,41,F,15,35,45,J,19,39,49
2,C,12,32,42,G,16,36,46,K,20,40,50
3,D,13,33,43,H,17,37,47,L,21,41,51